### PR TITLE
New example for the PyHC gallery

### PR DESCRIPTION
**Pull request by mwhv2**
This pull request features a new example, "retrieve_compress.py", for the PyHC gallery. I am a new software developer for the SunPy project, and this example was suggested to me based on some recent discussions in the PyHC community. 

I am somewhat new to Git/Github. So, please let me know if this pull request requires any additional editing.

### CODE REVIEW

**Review by sapols — APPROVED** [review]
Thanks for the new example, Matt!

**Comment by sapols** [comment]
@mwhv2 You'll notice I closed the PR without merging it. Our CI deployment process is broken right now so I've been doing the deployments manually. Your new example is live on our site: https://heliopython.org/gallery/generated/gallery/retrieve_compress.html#sphx-glr-generated-gallery-retrieve-compress-py

**Comment by sapols** [comment]
@mwhv2 Sorry to contact you so long after this PR, but your example recently broke for me and I'm trying to fix it. The line in the notebook `map_deconvolved = psf_.deconvolve(m_normalized, psf=psf)` fails with `ValueError: operands could not be broadcast together with shapes (4094,2048) (4096,2049)`. 

Using:
 - astropy=5.0.4
 - sunpy=3.1.8
 - aiapy=0.6.4

I didn't modify the notebook to my knowledge, so I wonder if the data source changed or something? 

If you wouldn't mind please, will you rerun this example on your machine and tell me if it succeeds or not? Thank you.

**Comment by mwhv2** [comment]
@sapols No worries! Interestingly, I do not get the `ValueError` when I run the example using the package versions you list. I do, however, run into separate issues when using sunpy=4.0 (and later). Additionally, several updates to sunpy and aiapy since I originally wrote this example should be taken into account for it to run correctly. If you would like, I'd be happy to update this example.

**Comment by sapols** [comment]
@mwhv2 Thanks for the quick response! Odd that you don't get the same `ValueError`. For my edification, could you please post a list of all the package versions you're using in your environment (e.g. with a `pip list`)?

Regardless, given this, the appropriate thing to do would be to update this example. I really appreciate you doing that, thank you. The new version of the gallery we're preparing to deploy accepts regular Jupyter Notebooks instead of that weird .py format you had to submit for this PR. So if you don't mind, please update your notebook then attach the .ipynb file to a comment here?

**Comment by sapols** [comment]
@mwhv2 Spontaneous thought I had: when you re-ran the notebook and did not get the `ValueError`, was it the case that the data files were already downloaded to your machine? I remembered when that's the case, the code is smart enough to not redownload anything.

**Comment by mwhv2** [comment]
@sapols I've attached a text document of the `pip list` to this. Since I do not have a CuPy compatible GPU, I typically test this example in Google Colab - FYI. The data files were re-downloaded each time I have run the notebook in Colab, and I have not run into the error.
[pip_list.txt](https://github.com/heliophysicsPy/gallery/files/10270426/pip_list.txt)

The updated notebook I've attached has rearranged the example somewhat following new guidelines in aiapy's documentation.
[retrieve_compress2.0.zip](https://github.com/heliophysicsPy/gallery/files/10270425/retrieve_compress2.0.zip)

(It's in a zip file because Github does not seem to like .ipynb files as attachements)

**Comment by sapols** [comment]
@mwhv2 Thank you! This is perfect. The new notebook works just fine. I still can't figure out why the old one works for you and not me, even comparing our package versions, but it's a moot point now. Appreciate the help.

**Pull request closed without merging**
